name: flutter_windowmanager
description: A Flutter plugin for manipulating Android WindowManager LayoutParams.
version: 0.3.0
homepage: https://github.com/adaptant-labs/flutter_windowmanager
repository: https://github.com/adaptant-labs/flutter_windowmanager
issue_tracker: https://github.com/adaptant-labs/flutter_windowmanager/issues

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.adaptant.labs.flutter_windowmanager
        pluginClass: FlutterWindowManagerPlugin
